data:
    data_dir: "data/Brain_Cancer"
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    img_size: [224, 224]
    preprocessed: "preprocessed/brain_cancer_mri_splits"

optimizer:
    name: "Adam"
    lr: 0.001
    weight_decay: 0.0001

scheduler:
    name: StepLR
    step_size: 4
    gamma: 0.1

train:
    epochs: 50
    batch_size: 32
    device: "cpu"

seed: 
    27

